### ISSUE TITLE
Exception with tagslam_node

### ISSUE THREAD

**Issue by e-guy** [berndpfrommer/tagslam_root#3]
Hi Bernd,

when running tagslame_node with my camera or rosbag, an "duplicate pose inserted" error  always occurred. Any help please!

![bag-ApritagDetect-Tagslam-tf](https://user-images.githubusercontent.com/25145810/67289694-95eb8480-f511-11e9-9e04-af15212ec30b.png)

![Screenshot from 2019-10-22 20-32-42](https://user-images.githubusercontent.com/25145810/67289274-ed3d2500-f510-11e9-8f60-3c36d7b52bbe.png)

**Comment by berndpfrommer** [comment]
Could you please post your cameras.yaml, tagslam.yaml, and camera_poses.yaml?

**Comment by e-guy** [comment]
Sorry, I only modified tag size in tagslam.yaml

**Comment by e-guy** [comment]
### tagslam.yaml
```
tagslam_parameters:
# optimizer mode: full (full optimization, no iSAM2 used)
#                 slow (use iSAM2, but test for error and use full if error is large)
#                 fast (iSAM2 only, no test for error)
# default: slow
  optimizer_mode: fast
# minimum angle [in degrees] between optical axis and tag surface
  minimum_viewing_angle: 12.0
# number of incremental updates before running
# a full graph optimization (default: 50)
  max_num_incremental_opt: 50
# estimated error of tag corner detector
  pixel_noise: 1.0
# maximum allowed subgraph error. If error is above that,
# the frame is thrown away, the measurement ignored.
  max_subgraph_error: 50.0
# Noise with which the subgraph absolute priors will be
# pinned down. This parameter usually does not need to be touched.
  subgraph_abs_prior_position_noise: 0.1
  subgraph_abs_prior_rotation_noise: 0.1
body_defaults:
  position_noise: 0.05
  rotation_noise: 0.01
default_body: grasp_lab
bodies:
 - grasp_lab:
     is_static: true
     default_tag_size: 0.12
     pose:
       position:
         x: 5
         y: 0
         z: 0
       rotation:
         x: 0
         y: 0
         z: 0
       position_noise:
         x: 0.0001
         y: 0.0001
         z: 0.0001
       rotation_noise:
         x: 1.0e-05
         y: 1.0e-05
         z: 1.0e-05
     type: simple
     tags:
     - id: 0
       size: 0.172
       pose:
         position:
           x: 0
           y: 0
           z: 0
         rotation:
           x: 0
           y: 0
           z: 0
         position_noise:
           x: 0.0001
           y: 0.0001
           z: 0.0001
         rotation_noise:
           x: 1.0e-05
           y: 1.0e-05
           z: 1.0e-05
 - rig:
     is_static: false
     type: simple

```

### cameras.yaml
```
cam0:
  camera_model: pinhole
  intrinsics: [1404.917, 1403.505, 962.317, 605.784]
  distortion_model: radtan
  distortion_coeffs: [-0.161604, 0.093674, -0.000037, -0.000336, 0.000000]
  resolution: [1920, 1200]
  rostopic: /pg_17274483/image_raw
  tagtopic: /detector/tags
  rig_body: rig
```

### camera_poses.yaml
```
cam0:
  pose:
    position:
      x: 10
      y: 0
      z: 0
    rotation:
      x: 0
      y: 0
      z: 0
    R:
      [ 1000000.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 
        0.00000000, 1000000.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 
        0.00000000, 0.00000000, 1000000.00000000, 0.00000000, 0.00000000, 0.00000000, 
        0.00000000, 0.00000000, 0.00000000, 1000000.00000000, 0.00000000, 0.00000000, 
        0.00000000, 0.00000000, 0.00000000, 0.00000000, 1000000.00000000, 0.00000000, 
        0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 1000000.00000000 ]
```
